apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: petclinic-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-petclinic-deploy
